# This file is machine-generated - editing it directly is not advised

julia_version = "1.11.7"
manifest_format = "2.0"
project_hash = "3bacde9025ee0ccf9b47f8c771f03d01d167dfe5"

[[deps.AdiabaticInvariant]]
git-tree-sha1 = "a1ed2b30dde536ee8d6003f2079957770cc6471d"
repo-rev = "main"
repo-url = ".."
uuid = "0e556e56-5d18-4166-9970-24ffe1271c72"
version = "1.0.0-DEV"
